name: 编译小米8SE内核 (sirius)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y bc bison ca-certificates flex gcc git make libssl-dev zip

      - name: 下载编译器
        run: |
          git clone https://github.com/mvaisakh/gcc-arm64.git --depth=1 gcc64

      - name: 拉取内核源码
        run: |
          git clone https://github.com/YxGHB/kernel_xiaomi_sdm710-1.git --depth=1 kernel
          cd kernel

      - name: 开始编译
        run: |
          cd kernel
          export PATH=$GITHUB_WORKSPACE/gcc64/bin:$PATH
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-elf-
          make sirius_defconfig
          make -j$(nproc) HOSTCFLAGS=-fcommon

      - name: 拉取AnyKernel3打包
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git --depth=1
          cp kernel/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cd AnyKernel3
          zip -r9 Kernel-sirius.zip *

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-sirius
          path: AnyKernel3/*.zip
